services:
  - type: web
    name: react-channel-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: SQL_HOST
        sync: false
      - key: SQL_USER
        sync: false
      - key: SQL_PASSWORD
        sync: false
      - key: SQL_DB_NAME
        sync: false
      - key: SQL_ADMIN_USER
        sync: false
      - key: SQL_ADMIN_PASSWORD
        sync: false
